### ISSUE TITLE
Incorrect translation of OPCODE_F32TOF16 and posibly OPCODE_F16TOF32

### ISSUE THREAD

**Issue by TiemoJung** [Unity-Technologies/HLSLcc#13]
Hi,

as the register type analysis of OPCODE_F32TOF16  and OPCODE_F16TOF32 are not implemented, the resulting translation into GLSL results in invalid GLSL as the target/source register type may be incorrect.

**Comment by TiemoJung** [comment]
Addition:
After further investigation it turnend out, that the implementation of  OPCODE_F32TOF16 and OPCODE_F16TOF32 translation are mixed up.

**Comment by aet** [comment]
should have been fixed for a while now, closing issue
