### ISSUE TITLE
Keeped in sync up to 5.6b10?

### ISSUE THREAD

**Issue by oscarbg** [Unity-Technologies/HLSLcc#17]
Hi,
just searching "Metal" in release notes up to b10 I see:

> Enabled UAV writes on fragment shaders for Metal.
> Fixed some corner cases in Metal compute buffers with counters
> Added cube array Texture support to OSX Metal

Just asking if that improvements required changes to HLSLcc or outside of it.. if changes needed will be nice to have HLSLcc updated also but for me big change will be Metal tesselation support in HLSLcc.. hope
 it's in 2017.1 beta in April and HLSLcc get's it by April also..

**Comment by strandborg** [comment]
Yeah, our internal HLSLcc has diverged a bit from what's currently in GitHub. I'm planning on pushing all new stuff here "soon" (meaning whenever I have time to do it)

**Comment by strandborg** [comment]
Pushed latest internal version to GitHub (roughly corresponding to the next 2018.2 beta)
