### ISSUE TITLE
ClearDependencyData() usage question

### ISSUE THREAD

**Issue by fitzymj** [Unity-Technologies/HLSLcc#18]
Would someone be able to clarify the need for the call to `psContext->ClearDependencyData()` in `ToGLSL::Translate()`?  I'm trying to get separable shader stages working, but the pixel shader translation responds to this call by wiping out the `GLSLCrossDependencyData` struct before processing its declarations (so every varying gets put in the wrong location).

I'm sure there must be a reason for it, but I'm not sure what it is!

Thanks,
Mike

**Comment by fitzymj** [comment]
Ah, I'm guessing it's related to this comment:
> HLSLCrossCompiler requires that hull shaders must be compiled before domain shaders, and the pixel shader must be compiled before all of the others.

So really `GLSLCrossDependencyData` is not applicable to separable shader stages at all, then, as it expects a single chain of shaders to be translated in a specific order?

I think what I want is a good way of getting more control over `GetVaryingLocation()`.  What I was trying was stuffing `varyingLocationsMap` before invoking the translation, but it seems like that won't work.

**Comment by strandborg** [comment]
Hi,

Yes, GLSLCrossDependencyData is a data structure that is used to carry information across compiling different shader stages. I haven't done any work towards separate shader objects, so no idea how easy or hard it would be to modify things to support that.
