### ISSUE TITLE
Metal tess support is coming in Unity 2018.1.. support here soon?

### ISSUE THREAD

**Issue by oscarbg** [Unity-Technologies/HLSLcc#30]
Hi,
just seen Unity roadmap mentions "Tessellation for Metal" being on track for 2018.1 release..
so considering we should be seeing support for it in first public beta possibly coming this year it might be very well implemented by now..
would be nice if HLSLcc Metal tesselation support could be posted soon (christmas present for this year? :-) )..
thanks..

**Comment by oscarbg** [comment]
any update on HLSLcc..
has Unity switched to another framework for translating HLSL to Metal tesselation?
thanks..

**Comment by aet** [comment]
hi, obviously the changes have been on HLSLcc github source for a while, just not reacting to issues very well. :) the master just got updated, bringing along additional metal tessellation codegen fixes for some rare cases
